### ISSUE TITLE
graph pod expects graph-ldap-bind-password in ldap-bind-secrets

### ISSUE THREAD

**Issue by jamu85** [owncloud/ocis-charts#133]
The documentation is missing the `graph-ldap-bind-password` in `ldap-bind-secrets` when setting up cis with an external ids and ldap provider

````
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  6m36s                   default-scheduler  Successfully assigned cloud-idp/graph-5994fd888d-fskff to worker-ash-bvv
  Warning  Failed     4m22s (x12 over 6m36s)  kubelet            Error: couldn't find key graph-ldap-bind-password in Secret cloud-idp/ldap-bind-secrets
  Normal   Pulled     96s (x25 over 6m36s)    kubelet            Container image "owncloud/ocis:2.0.0" already present on machine
````
Solved by adding it to the secret
````
apiVersion: v1
kind: Secret
metadata:
  name: ldap-bind-secrets
  namespace: cloud-idp
type: Opaque
data:
  # Base64 encoded password for the LDAP bind user.
  reva-ldap-bind-password: notSecretPassword (as base64 decoded string)
  graph-ldap-bind-password: notSecretPassword (as base64 decoded string)
````
