### ISSUE TITLE
oidc without external ldap?

### ISSUE THREAD

**Issue by ishioni** [owncloud/ocis-charts#137]
I'm trying to hookup [authentik](https://goauthentik.io/) with ocis, but it seems the helm chart requires an external ldap server when using authentik. I'm confused how to get that going?

**Comment by s0jnik** [comment]
Hi @ishioni 
I try to achieve the same. I'm not done yet but I can give you some hints and explain what I did.

In my understanding, this helm chart enforces utilization of an external ldap if you want to use an external idp.
There are examples with only using an odic provider but keep using the ocis internal ldap server eg. [here](https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_keycloak/docker-compose.yml) but this chart probably focuses on integration with an external Keycloak plus openldap.

In my setup, I utilized the ldap service in Authentik in order to handle all user management via Authentik.
For that, I created a Application, Provider and outpost, not only for OIDC but also for LDAP
Create a Application like
![image](https://user-images.githubusercontent.com/49803228/209089833-50e1bbae-8603-4a74-a571-ceeca8aff67a.png)
Create the LDAP Provider like
![image](https://user-images.githubusercontent.com/49803228/209090071-c1be5c76-e280-4930-a236-41e8bf7224f8.png)
And finally the outpost
![image](https://user-images.githubusercontent.com/49803228/209091495-af7eeba2-a658-4d41-8eba-38ae99b60f25.png)
Make sure, that you select 'Local Kubernetes Cluster' at Integration as this will create a service in the namespace of authentik

````
➜  ~ k get services -n identity
NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                    AGE
ak-outpost-ocis-ldap            ClusterIP   10.43.226.252   <none>        389/TCP,636/TCP,9300/TCP   11d
authentik                       ClusterIP   10.43.66.29     <none>        9100/TCP,80/TCP            14d
authentik-postgresql            ClusterIP   10.43.180.29    <none>        5432/TCP                   14d
authentik-postgresql-headless   ClusterIP   None            <none>        5432/TCP                   14d
authentik-redis-headless        ClusterIP   None            <none>        6379/TCP                   14d
authentik-redis-master          ClusterIP   10.43.128.3     <none>        6379/TCP                   14d
````

The service `ak-outpost-ocis-ldap` can be used as ldap server for ocis via its service domain
````
    # LDAP related settings.
    ldap:
      # -- URI to connect to the LDAP secure server.
      uri: ldap://ak-outpost-ocis-ldap.identity.svc.cluster.local
````

For the bindn I have created a service account 
![image](https://user-images.githubusercontent.com/49803228/209091965-d340b5ac-cf63-4c08-ad53-d9b6bcc1d653.png)
That i use in the chart for `bindDN: cn=ocis,ou=users,dc=ldap,dc=goauthentik,dc=io` 
The password is provided as secret to the deployment as reva-ldap-bind-password and as graph-ldap-bind-password
````
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-bind-secrets
  namespace: cloud-idp
type: Opaque
data:
  # Base64 encoded password for the LDAP bind user.
  reva-ldap-bind-password: bindnsecretasbase64encodedstring==
  graph-ldap-bind-password: bindnsecretasbase64encodedstring==
````

If I spawn a bash in a container on the cluster and ldapsearch for the users in my Authentik Instance by using the ocis binddn and the the setup as described above, I get the users back and I'm able to connect to the ldap server.

````
➜  ~ kubectl run tmp-shell --restart=Never --rm -i --tty --image ubuntu -- /bin/bash
If you don't see a command prompt, try pressing enter.
root@tmp-shell:/#
root@tmp-shell:/# apt update
...
root@tmp-shell:/# apt install ldap-utils
...
root@tmp-shell:/# ldapsearch -x -H ldap://ak-outpost-ocis-ldap.identity.svc.cluster.local -b dc=ldap,dc=goauthentik,dc=io -D "cn=ocis,ou=users,dc=ldap,dc=goauthentik,dc=io" -w bindnsecretasbase64decodedstring
# extended LDIF
#
# LDAPv3
# base <dc=ldap,dc=goauthentik,dc=io> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# ldap.goauthentik.io
dn: DC=ldap,DC=goauthentik,DC=io
distinguishedName: DC=ldap,DC=goauthentik,DC=io
objectClass: top
objectClass: domain
supportedLDAPVersion: 3
namingContexts: DC=ldap,DC=goauthentik,DC=io
namingContexts: ou=users,dc=ldap,dc=goauthentik,dc=io
namingContexts: ou=groups,dc=ldap,dc=goauthentik,dc=io
namingContexts: ou=virtual-groups,dc=ldap,dc=goauthentik,dc=io
vendorName: goauthentik.io
vendorVersion: authentik LDAP Outpost Version 2022.11.3

# users, ldap.goauthentik.io
dn: ou=users,dc=ldap,dc=goauthentik,dc=io
distinguishedName: ou=users,dc=ldap,dc=goauthentik,dc=io
objectClass: top
objectClass: nsContainer
commonName: users

# akadmin, users, ldap.goauthentik.io
dn: cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/ldap/active: true
sAMAccountName: akadmin
name: authentik Default Admin
mail: jan@mydomain.com
gidNumber: 2001
uidNumber: 2001
memberOf: cn=authentik Admins,ou=groups,dc=ldap,dc=goauthentik,dc=io
memberOf: cn=cloud,ou=groups,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/ldap/superuser: true
cn: akadmin
uid: dd42cda266c308e3107ac0c1b1b240fd06b764f97f979ff56fc726f1dfe4a86e
displayName: authentik Default Admin
objectClass: user
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: goauthentik.io/ldap/user

# ak-outpost-4b4cff8fb1c844449d34d15f1e688082, users, ldap.goauthentik.io
dn: cn=ak-outpost-4b4cff8fb1c844449d34d15f1e688082,ou=users,dc=ldap,dc=goauthe
 ntik,dc=io
goauthentik.io/user/override-ips: true
goauthentik.io/user/service-account: true
uid: 775f647c64e63dec07bc0ef523cb10607334bbbac9c9c2b055a010534d42dc26
displayName: Outpost authentik Embedded Outpost Service-Account
mail:
uidNumber: 2003
gidNumber: 2003
goauthentik.io/ldap/active: true
goauthentik.io/ldap/superuser: false
cn: ak-outpost-4b4cff8fb1c844449d34d15f1e688082
sAMAccountName: ak-outpost-4b4cff8fb1c844449d34d15f1e688082
name: Outpost authentik Embedded Outpost Service-Account
objectClass: user
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: goauthentik.io/ldap/user

# ak-outpost-be1b48c988da4ad99b24c25ed7cae07c, users, ldap.goauthentik.io
dn: cn=ak-outpost-be1b48c988da4ad99b24c25ed7cae07c,ou=users,dc=ldap,dc=goauthe
 ntik,dc=io
goauthentik.io/user/override-ips: true
goauthentik.io/user/service-account: true
cn: ak-outpost-be1b48c988da4ad99b24c25ed7cae07c
sAMAccountName: ak-outpost-be1b48c988da4ad99b24c25ed7cae07c
name: Outpost ocis-ldap Service-Account
displayName: Outpost ocis-ldap Service-Account
objectClass: user
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: goauthentik.io/ldap/user
goauthentik.io/ldap/active: true
goauthentik.io/ldap/superuser: false
uid: 3d82e6875b56fdbc1fbc41e8f70afa3007c4e3c1572d4e774994d03c46d5dc96
mail:
uidNumber: 2008
gidNumber: 2008

# ocis, users, ldap.goauthentik.io
dn: cn=ocis,ou=users,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/user/token-expires: false
goauthentik.io/user/service-account: true
displayName: ocis
mail:
gidNumber: 2005
goauthentik.io/ldap/superuser: false
cn: ocis
name: ocis
uid: 2f466661f7090cb8e4b3a33022c7892550910daf77fb8c80f321f8edc994a395
objectClass: user
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: goauthentik.io/ldap/user
uidNumber: 2005
memberOf: cn=ocis,ou=groups,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/ldap/active: true
sAMAccountName: ocis

# groups, ldap.goauthentik.io
dn: ou=groups,dc=ldap,dc=goauthentik,dc=io
distinguishedName: ou=groups,dc=ldap,dc=goauthentik,dc=io
objectClass: top
objectClass: nsContainer
commonName: groups

# authentik Admins, groups, ldap.goauthentik.io
dn: cn=authentik Admins,ou=groups,dc=ldap,dc=goauthentik,dc=io
uid: 6fa94022-d756-4ac2-b82f-e329c3617519
sAMAccountName: authentik Admins
gidNumber: 18842
objectClass: group
objectClass: groupOfUniqueNames
objectClass: groupOfNames
objectClass: goauthentik.io/ldap/group
member: cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/ldap/superuser: true
cn: authentik Admins

# cloud, groups, ldap.goauthentik.io
dn: cn=cloud,ou=groups,dc=ldap,dc=goauthentik,dc=io
objectClass: group
objectClass: groupOfUniqueNames
objectClass: groupOfNames
objectClass: goauthentik.io/ldap/group
member: cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/ldap/superuser: false
cn: cloud
uid: a0cbf3ca-ef17-453b-a000-5094b2836ea2
sAMAccountName: cloud
gidNumber: 25373

# ocis, groups, ldap.goauthentik.io
dn: cn=ocis,ou=groups,dc=ldap,dc=goauthentik,dc=io
cn: ocis
uid: b337f954-785b-403a-ab8f-e4fa3a597b42
sAMAccountName: ocis
gidNumber: 27822
objectClass: group
objectClass: groupOfUniqueNames
objectClass: groupOfNames
objectClass: goauthentik.io/ldap/group
member: cn=ocis,ou=users,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/ldap/superuser: false

# virtual-groups, ldap.goauthentik.io
dn: ou=virtual-groups,dc=ldap,dc=goauthentik,dc=io
distinguishedName: ou=virtual-groups,dc=ldap,dc=goauthentik,dc=io
objectClass: top
objectClass: nsContainer
commonName: virtual-groups

# akadmin, virtual-groups, ldap.goauthentik.io
dn: cn=akadmin,ou=virtual-groups,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/ldap/superuser: false
cn: akadmin
uid: dd42cda266c308e3107ac0c1b1b240fd06b764f97f979ff56fc726f1dfe4a86e
sAMAccountName: akadmin
gidNumber: 2001
objectClass: group
objectClass: groupOfUniqueNames
objectClass: groupOfNames
objectClass: goauthentik.io/ldap/group
objectClass: goauthentik.io/ldap/virtual-group
member: cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io

# ak-outpost-4b4cff8fb1c844449d34d15f1e688082, virtual-groups, ldap.goauthentik
 .io
dn: cn=ak-outpost-4b4cff8fb1c844449d34d15f1e688082,ou=virtual-groups,dc=ldap,d
 c=goauthentik,dc=io
uid: 775f647c64e63dec07bc0ef523cb10607334bbbac9c9c2b055a010534d42dc26
sAMAccountName: ak-outpost-4b4cff8fb1c844449d34d15f1e688082
gidNumber: 2003
objectClass: group
objectClass: groupOfUniqueNames
objectClass: groupOfNames
objectClass: goauthentik.io/ldap/group
objectClass: goauthentik.io/ldap/virtual-group
member: cn=ak-outpost-4b4cff8fb1c844449d34d15f1e688082,ou=users,dc=ldap,dc=goa
 uthentik,dc=io
goauthentik.io/ldap/superuser: false
cn: ak-outpost-4b4cff8fb1c844449d34d15f1e688082

# ak-outpost-be1b48c988da4ad99b24c25ed7cae07c, virtual-groups, ldap.goauthentik
 .io
dn: cn=ak-outpost-be1b48c988da4ad99b24c25ed7cae07c,ou=virtual-groups,dc=ldap,d
 c=goauthentik,dc=io
goauthentik.io/ldap/superuser: false
cn: ak-outpost-be1b48c988da4ad99b24c25ed7cae07c
uid: 3d82e6875b56fdbc1fbc41e8f70afa3007c4e3c1572d4e774994d03c46d5dc96
sAMAccountName: ak-outpost-be1b48c988da4ad99b24c25ed7cae07c
gidNumber: 2008
objectClass: group
objectClass: groupOfUniqueNames
objectClass: groupOfNames
objectClass: goauthentik.io/ldap/group
objectClass: goauthentik.io/ldap/virtual-group
member: cn=ak-outpost-be1b48c988da4ad99b24c25ed7cae07c,ou=users,dc=ldap,dc=goa
 uthentik,dc=io

# ocis, virtual-groups, ldap.goauthentik.io
dn: cn=ocis,ou=virtual-groups,dc=ldap,dc=goauthentik,dc=io
goauthentik.io/ldap/superuser: false
cn: ocis
uid: 2f466661f7090cb8e4b3a33022c7892550910daf77fb8c80f321f8edc994a395
sAMAccountName: ocis
gidNumber: 2005
objectClass: group
objectClass: groupOfUniqueNames
objectClass: groupOfNames
objectClass: goauthentik.io/ldap/group
objectClass: goauthentik.io/ldap/virtual-group
member: cn=ocis,ou=users,dc=ldap,dc=goauthentik,dc=io

# search result
search: 2
result: 0 Success

# numResponses: 18
# numEntries: 17
````

I have no idea, if the following parameters in the chart are configured correctly.

````
     user:
        schema:
          # -- LDAP Attribute to use as the unique id for users. This should be a stable globally unique id like a UUID.
          id: uid
          # -- Set this to true if the defined `id` attribute for users is of the `OCTETSTRING` syntax. This is e.g. required when using the `objectGUID` attribute of Active Directory for the user ID`s.
          idIsOctetString: false
          # -- LDAP Attribute to use for the email address of users.
          mail: mail
          # -- LDAP Attribute to use for the displayname of users.
          displayName: displayname
          # -- LDAP Attribute to use for username of users.
          userName: uid
        # -- Search base DN for looking up LDAP users.
        baseDN: DC=ldap,DC=goauthentik,DC=io
        # -- LDAP search scope to use when looking up users. Supported values are `base`, `one` and `sub`.
        scope: sub
        # -- Type of substring search filter to use for substring searches for users. Possible values: `initial` for doing prefix only searches, `final` for doing suffix only searches or `any` for doing full substring searches
        substringFilterType: any
        # -- LDAP filter to add to the default filters for user search like `(objectclass=ownCloud)`.
        filter:
        # -- The object class to use for users in the default user search filter like `inetOrgPerson`.
        objectClass: user
      group:
        schema:
          # -- LDAP Attribute to use as the unique ID for groups. This should be a stable globally unique ID like a UUID.
          id: uid
          # -- Set this to true if the defined `id` attribute for groups is of the `OCTETSTRING` syntax. This is e.g. required when using the `objectGUID` attribute of Active Directory for the group ID`s.
          idIsOctetString: false
          # -- LDAP Attribute to use for the email address of groups (can be empty).
          mail: mail
          # -- LDAP Attribute to use for the displayname of groups (often the same as groupname attribute).
          displayName: cn
          # -- LDAP Attribute to use for the name of groups.
          groupName: cn
          # -- LDAP Attribute that is used for group members.
          member: member
        # -- Search base DN for looking up LDAP groups.
        baseDN: DC=ldap,DC=goauthentik,DC=io
        # -- LDAP search scope to use when looking up groups. Supported values are `base`, `one` and `sub`.
        scope: sub
        # -- LDAP filter to add to the default filters for group searches.
        filter:
        # -- The object class to use for groups in the default group search filter like `groupOfNames`.
        objectClass: group
````

My Authentication flow fails at the redirect after ocis shows the message that I successfully logged in because the /token endpoint of my Authentik instance return a 504. I assume this is related to a false setting above.

@wkloucek @butonic 
Can you help @ishioni and me with the setup above?

**Comment by s0jnik** [comment]
Sorry, my bad. It returns 400 for the token endpoint not 504
````
Failed to load resource: the server responded with a status of 400 ()
````
````
{
    "error": "invalid_client",
    "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"
}
````
![image](https://user-images.githubusercontent.com/49803228/209345310-8637008a-bc74-4cdc-b4d6-5ea33a480b0c.png)

I haven't looked at it closely enough last time I worked on it. Lets see how I can move ahead with this new failure message

> What do you have in this config section?

Exactly this
````
     user:
        schema:
          # -- LDAP Attribute to use as the unique id for users. This should be a stable globally unique id like a UUID.
          id: uid
          # -- Set this to true if the defined `id` attribute for users is of the `OCTETSTRING` syntax. This is e.g. required when using the `objectGUID` attribute of Active Directory for the user ID`s.
          idIsOctetString: false
          # -- LDAP Attribute to use for the email address of users.
          mail: mail
          # -- LDAP Attribute to use for the displayname of users.
          displayName: displayname
          # -- LDAP Attribute to use for username of users.
          userName: uid
        # -- Search base DN for looking up LDAP users.
        baseDN: DC=ldap,DC=goauthentik,DC=io
        # -- LDAP search scope to use when looking up users. Supported values are `base`, `one` and `sub`.
        scope: sub
        # -- Type of substring search filter to use for substring searches for users. Possible values: `initial` for doing prefix only searches, `final` for doing suffix only searches or `any` for doing full substring searches
        substringFilterType: any
        # -- LDAP filter to add to the default filters for user search like `(objectclass=ownCloud)`.
        filter:
        # -- The object class to use for users in the default user search filter like `inetOrgPerson`.
        objectClass: user
      group:
        schema:
          # -- LDAP Attribute to use as the unique ID for groups. This should be a stable globally unique ID like a UUID.
          id: uid
          # -- Set this to true if the defined `id` attribute for groups is of the `OCTETSTRING` syntax. This is e.g. required when using the `objectGUID` attribute of Active Directory for the group ID`s.
          idIsOctetString: false
          # -- LDAP Attribute to use for the email address of groups (can be empty).
          mail: mail
          # -- LDAP Attribute to use for the displayname of groups (often the same as groupname attribute).
          displayName: cn
          # -- LDAP Attribute to use for the name of groups.
          groupName: cn
          # -- LDAP Attribute that is used for group members.
          member: member
        # -- Search base DN for looking up LDAP groups.
        baseDN: DC=ldap,DC=goauthentik,DC=io
        # -- LDAP search scope to use when looking up groups. Supported values are `base`, `one` and `sub`.
        scope: sub
        # -- LDAP filter to add to the default filters for group searches.
        filter:
        # -- The object class to use for groups in the default group search filter like `groupOfNames`.
        objectClass: group
````

**Comment by camrossi** [comment]
@wkloucek I am trying exactly the same but I am also stuck with the same 
```
{
    "error": "invalid_client",
    "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"
}
```
I have this config but I can't seems to find a way to pass the `Client Secret`
At least that is what I am doing with another app that works fine with Authentik. 
```
features:
  externalUserManagement:
    enabled: true
    oidc:
      issuerURI: https://authentik.camsab.me/application/o/ocis/
      webClientID: <MyKeyID>
      accessTokenVerifyMethod: "jwt"
      userIDClaim: ocis.user.uuid
      userIDClaimAttributeMapping: userid
      roleAssignment:
        enabled: false
    ldap:
      writeable: false
      uri: ldap://ak-outpost-ldap.authentik.svc.cluster.local
      certTrusted: true
      insecure: true
      bindDN: "uid=ocis,dc=ldap,dc=camsab,dc=me"
      useServerUUID: true

secretRefs:
  ldapSecretRef: "ldap-bind-secrets"
```

More in general would be really helpful to have a working example for `externalUserManagement`

**Comment by wkloucek** [comment]
> More in general would be really helpful to have a working example for externalUserManagement

We have it for Keycloak with OpenLDAP: https://github.com/owncloud/ocis-charts/blob/96fa3164b7d0be9d6553c9a4d4d210373388ce78/deployments/external-user-management/helmfile.yaml#L346-L381

I'd happy to review / merge a Authentik based example, too. Even if you'd you provide a not yet working Authelia deployment example as pull request, I'd happy to help debugging it!

**Comment by camrossi** [comment]
Actually I managed to get it all working took a while but I do wanna create either an issue or a PR with a sanitised config. I will try to have something done in the next few days or next week. @wkloucek would you prefer I do a PR, open an issue, or add it here?

**Comment by wkloucek** [comment]
> Actually I managed to get it all working took a while but I do wanna create either an issue or a PR with a sanitised config. I will try to have something done in the next few days or next week. @wkloucek would you prefer I do a PR, open an issue, or add it here?

Do you already have it in a helmfile? Or could could you provide the values, you passed to `helm install / upgrade` and the charts / versions you have used? I'd honestly prefer a PR, if you'd just dump the value files there would be sufficient for me. Then I can take over or review.

(as you aleady said, please no secrets / domains of your installation)

**Comment by camrossi** [comment]
> > Actually I managed to get it all working took a while but I do wanna create either an issue or a PR with a sanitised config. I will try to have something done in the next few days or next week. @wkloucek would you prefer I do a PR, open an issue, or add it here?
> 
> Do you already have it in a helmfile? Or could could you provide the values, you passed to `helm install / upgrade` and the charts / versions you have used? I'd honestly prefer a PR, if you'd just dump the value files there would be sufficient for me. Then I can take over or review.
> 
> (as you aleady said, please no secrets / domains of your installation)

So I have been doing a lot of testing and I am stuck on one thing.. .that I wanna fix before I push the PR/Helm Chart. 
Currently I am having the secrets auto generated by the chart and I use argo to push the configs. I realised that if I make any changes to the Charts the secret are re-generated and over-written resulting in a broken installation...then only way i can fix it is to re-install (and loose all the data)

For now a workaround is to deselect the secrets from ArgoCD when I push a chart update or (I guess but didn't try) create the secrets manually. 
![image](https://github.com/owncloud/ocis-charts/assets/16535101/73507062-e114-444d-a063-f567944e868d)

What am I missing here?

**Comment by camrossi** [comment]
Quick update I just defined all my secrets manually (using sealed secrets) and now I can update the helm values file without breaking anything. Let me know if this is expected/they way to do it with ArgoCD and if so will document this as well in the PR :) 
```
secretRefs:
  ldapSecretRef: "ldap-bind-secrets"
  jwtSecretRef: "jwt-secret"
  machineAuthApiKeySecretRef: "machine-auth-api-key"
  storagesystemJwtSecretRef: "storage-system-jwt-secret"
  storagesystemSecretRef: "storage-system"
  thumbnailsSecretRef: "thumbnails-transfer-secret"
  transferSecretSecretRef: "transfer-secret"
```
