### ISSUE TITLE
add configuration for role quotas

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#150]
see https://owncloud.dev/services/proxy/configuration/ -> `role_quotas`

Example:

```yaml
role_quotas:
  # Role 1 2GB
  d7beeea8-8ff4-406b-8fb6-ab2dd81e6b11: 2000000000
  # Role 2 100GB
  71881883-1768-46bd-a24d-a356a2afdf7f: 100000000000
  # Role 3 100GB
  2aadd357-682c-406b-8874-293091995fdd: 100000000000
```
