### ISSUE TITLE
expose imagePullSecrets configuration

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#152]
Example:

```
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: <your-private-image>
  imagePullSecrets:
  - name: regcred
```
