### ISSUE TITLE
Prometheus Operator CRDs - ServiceMonitor

### ISSUE THREAD

**Issue by genofire** [owncloud/ocis-charts#162]
it would be nice, that this helmcharts deploy also a ServiceMonitor, which select all Service (and there behind all Pods) to scrape all Metrics.

https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.ServiceMonitor

**Comment by genofire** [comment]
Values e.g.:

```yaml
prometheus:
  servicemonitor:
    enabled: true
    labels:
      release: "kube-prometheus-stack"
  rules:
    # will deploy alert rules
    enabled: true
    labels:
      release: "kube-prometheus-stack"
    additionalRules: []
grafana:
  dashboards:
    enabled: true
```

PS: The labels `release=kube-prometheus-stack` is setup with the helmchart of the Prometheus Operator.
