### ISSUE TITLE
allow branding of ownCloud Web

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#177]
- allow to change `WEB_UI_THEME_PATH`
- allow custom css
```yaml
web:
  config:
      styles:
        - href: /themes/<theme-name>/theme.css
```
- allow to mount a theme into the Web pod

see also https://github.com/owncloud/ocis/pull/6032
