### ISSUE TITLE
[Bug] Remove blank lines in web service YAML

### ISSUE THREAD

**Issue by d7oc** [owncloud/ocis-charts#183]
Currently the deployment YAML for the web service looks like:

```YAML
            - name: WEB_HTTP_ADDR
              value: 0.0.0.0:9100
            - name: WEB_DEBUG_ADDR
              value: 0.0.0.0:9104

            - name: WEB_OIDC_AUTHORITY

              value: "https://keycloak.owncloud.test:4443/realms/test"


            - name: WEB_UI_THEME_SERVER

              value: https://ocis.owncloud.test
```

The blank lines in between should be removed.

**Comment by d7oc** [comment]
Just to add, the output after the fix:

```YAML
            - name: WEB_HTTP_ADDR
              value: 0.0.0.0:9100
            - name: WEB_DEBUG_ADDR
              value: 0.0.0.0:9104

            - name: WEB_OIDC_AUTHORITY
              value: "https://keycloak.owncloud.test:4443/realms/test"

            - name: WEB_UI_THEME_SERVER
              value: https://ocis.owncloud.test

            - name: WEB_UI_CONFIG_SERVER
              value: "https://ocis.owncloud.test"
```
