### ISSUE TITLE
Add an env map as a fallback for options not yet supported

### ISSUE THREAD

**Issue by NexZhu** [owncloud/ocis-charts#20]
I'm currently using OCIS with this chart: https://github.com/k8s-at-home/charts/blob/master/charts/stable/owncloud-ocis/
and setting options like this:
```yaml
# -- environment variables. See more environment variables in the [ownclohttps://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml# @default -- See below
env:
  OCIS_LOG_LEVEL: debug #info
  # -- Set the container timezone
  TZ: UTC
  # PROXY_ENABLE_BASIC_AUTH: "true"
  ACCOUNTS_DEMO_USERS_AND_GROUPS: false
  OCIS_URL: https://
  PROXY_TLS: false
  # OIDC
  PROXY_AUTOPROVISION_ACCOUNTS: "true"
  PROXY_OIDC_ISSUER: https://
  WEB_OIDC_AUTHORITY: https://
  WEB_OIDC_CLIENT_ID: owncloud-web
  STORAGE_OIDC_ISSUER: https://
  STORAGE_FRONTEND_PUBLIC_URL: http://localhost:9200
  # activate s3ng storage driver
  STORAGE_HOME_DRIVER: s3ng
  STORAGE_USERS_DRIVER: s3ng
  STORAGE_METADATA_DRIVER: ocis # keep metadata on ocis storage since this are only small files atm
  STORAGE_USERS_DRIVER_S3NG_ENDPOINT: https://
  STORAGE_USERS_DRIVER_S3NG_REGION: 
  # App registry
  STORAGE_APP_REGISTRY_MIMETYPES_JSON: /config/mimetypes.json
  # Theme
  WEB_UI_THEME_SERVER: https://public.internetapi.cn
  WEB_UI_THEME_PATH: /internal/ocis-theme.json
```

Can we also add a env map as a fallback for options not yet supported? So people can start using this chart sooner.
