### ISSUE TITLE
`cleanUpExpiredUploads` job not working with S3ng

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#277]
When configuring S3ng as `storageBackend.driver` and enabling the `maintenance.cleanUpExpiredUploads` job, like following:

```
services:
  storageusers:
    storageBackend:
      driver: s3ng
      driverConfig:
        s3ng:
          ...
    maintenance:
      cleanUpExpiredUploads:
        enabled: true
```

The pods, executing the job, will show following message:

```bash
$ kubectl logs -f -n ocis pod/storage-users-clean-expired-uploads-28071867-7qtv4 
Failed to initialize filesystem driver 's3ng'
```
