### ISSUE TITLE
ingress should support https

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-charts#352]
Currently, ingress is hardcoded to http it should be configurable and default to https. If a deployment sits behind an additional reverse proxy that forwards requests to http that should be an extra configuration step.

**Comment by butonic** [comment]
hmmm ... I may misunderstand how the rules work

**Comment by butonic** [comment]
For the default openshift IngressController, the easiest way to use https is to use this annotation:
```
 - ingress:
     enabled: true 
     annotations:
       route.openshift.io/termination: edge
```
