### ISSUE TITLE
Can't use LDAP

### ISSUE THREAD

**Issue by Whidix** [owncloud/ocis-charts#402]
Hello,

I'm trying to set up owncloud with ldap authentication, but I'm unable to make it work.
Owncloud always try to authenticate me with oidc on https://idp.owncloud.test/realms/ocis/.well-known/openid-configuration.

Here are some important values that I edited, maybe am I missing something ?

```
features:
  basicAuthentication: true
  externalUserManagement:
    # LDAP related settings.
    enabled: true
    adminUUID: "admin"
     ldap:
      writeable: false
      insecure: true
      . . .
```

Thanks for your help.

**Comment by wkloucek** [comment]
The documentation comments in the values.yaml state following:

https://github.com/owncloud/ocis-charts/blob/5c854bc2ac38ee2326039f96576ae5b050d3ce16/charts/ocis/values.yaml#L251-L254C61


This means you also change the OIDC identity provider settings:

https://github.com/owncloud/ocis-charts/blob/5c854bc2ac38ee2326039f96576ae5b050d3ce16/charts/ocis/values.yaml#L261-L265

I admit, that we should not have a default value here. We should refuse the installation if external user management is enabled and not external OIDC identity provider is configured.

**Comment by wkloucek** [comment]
oCIS ships a LDAP and IDP service by default. You can omit one or both of them.

The oCIS Helm chart is more opinionated and does only allow to use both for development or small installation purposes. This is because the chart aims at high available and scalable installations. Neither the oCIS LDAP nor the IDP services are 
currently  (horizontally) scalable. Therefore we expect them to be replaced both for the Helm Chart (also to reduce configuration permutations)

**Comment by Whidix** [comment]
Sorry, what I mean is that I have an external ldap server and I want to use it as a users provider.

**Comment by Whidix** [comment]
Just ouf of curiousity, what is the point of having both an external ldap and oidc provider at the same time ? Both of them can do authentification, and in my case, the keycloak use ldap as it's source.

I tried too use keycloak before opening this issue but it didn't work, where am I supposed to register the token generated by keycloak ?

**Comment by Whidix** [comment]
Thank you, I have one last question.
I ended up with this "error":
![image](https://github.com/owncloud/ocis-charts/assets/31294015/087a6809-9e4c-43ef-b911-e0733b372a32)

I want to use my users uid (ldap ones) which are equals to  usernames of keycloak users. I don't understand how to map it to ocis.
For example with my user (uid=whidix), I have :

```
features:
  basicAuthentication: true
  externalUserManagement:
    enabled: true
    adminUUID: "whidix"
    oidc:
      issuerURI: "https://auth.example.com/realms/production"
      webClientID: "owncloud"
      userIDClaim: ocis.user.uuid #I tried ocis.user.username
      userIDClaimAttributeMapping: userid
    ldap:
      writeable: false
      uri: ldaps://ldap.example.com
      certTrusted: true 
      insecure: true
      bindDN: uid=client-consult,ou=scripts,ou=inp-net,o=inp,dc=example,dc=com
      useServerUUID: false
      user:
        schema:
          id: uid
          idIsOctetString: false
          mail: mail
          displayName: displayname
          userName: uid
          # -- LDAP Attribute to distinguish between 'Member' and 'Guest' users. Default is 'ownCloudUserType'.
          userType: ownCloudUserType
        baseDN: dc=example,dc=com
        scope: sub
        substringFilterType: any
        filter:
        objectClass: inetOrgPerson
      group:
        schema:
          id: cn
          idIsOctetString: false
          mail: mailAlias
          displayName: displayName
          groupName: displayName
          member:  memberUid
        baseDN: dc=example,dc=com
        scope: sub
        filter:
        objectClass: Club
```
