### ISSUE TITLE
support custom ca chain

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-charts#403]
In some deployments a self signed root CA is used to verify eg the certificate of S3. There are multiple ways to make ocis aware of one or more custom root CAs:
1. build a custom container to include the correct CA chain
2. set the `SSL_CERT_DIR=/etc/ssl/certs` env var and mount a certificate chain to eg. `/etc/ssl/certs/custom.pem`. 

SSL_CERT_DIR will cause golang to read all certificates in that dir.

**Comment by wkloucek** [comment]
CA chain is already partly supported for eg. LDAP.

we need a clear strategy how to deal with this:
- HTTP clients
- Store / Caches
- Message Bus
- Office Integrations / WOPI
- Email Server
- Tika

So far we only have a option to switch of certificat validation.

Related:
- https://github.com/owncloud/ocis-charts/issues/109

**Comment by butonic** [comment]
Workaround in https://github.com/owncloud/ocis-charts/issues/420#issue-1976482355

**Comment by butonic** [comment]
`SSL_CERT_DIR` is read by golang to pick up custom certificates. We can use it to make every pod containing a golang binary read a a custom CA.

**Comment by dj4oC** [comment]
@d7oc we need to prioritize this, because it is blocking currently @b1schumacher

**Comment by dj4oC** [comment]
@b1schumacher does @butonic - solution not work?
 https://github.com/owncloud/ocis-charts/issues/420#issue-1976482355
If not, may I ask you to create a pull request to overcome this limitation?

**Comment by b1schumacher** [comment]
The problem we are facing now, is that this is not just a S3 Problem but rather a global problem. We need the chain in every pod that needs to communicate with a service that is secured by the custom ca chain.

**Comment by dj4oC** [comment]
So basically all service definitions need to be extended by these 10 lines?

**Comment by d7oc** [comment]
There are common templates for all services. There might be one which can be used so just the template is enhanced and you get all for free.

**Comment by dj4oC** [comment]
> There are common templates for all services. There might be one which can be used so just the template is enhanced and you get all for free.

Does that mean we have a even faster implementation?

**Comment by wkloucek** [comment]
How do other Helm Charts solve this challenge? I'd always prefer to stick to practices that are also used by charts like bitnami / grafana.

**Comment by wkloucek** [comment]
Seems like Bitnami charts have something like this:

```yaml
## TLS configuration
##
tls:
  ## @param tls.enabled Enable TLS traffic
  ##
  enabled: false
  ## @param tls.authClients Require clients to authenticate
  ##
  authClients: true
  ## @param tls.autoGenerated Enable autogenerated certificates
  ##
  autoGenerated: false
  ## @param tls.existingSecret The name of the existing secret that contains the TLS certificates
  ##
  existingSecret: ""
  ## @param tls.certificatesSecret DEPRECATED. Use existingSecret instead.
  ##
  certificatesSecret: ""
  ## @param tls.certFilename Certificate filename
  ##
  certFilename: ""
  ## @param tls.certKeyFilename Certificate Key filename
  ##
  certKeyFilename: ""
  ## @param tls.certCAFilename CA Certificate filename
  ##
  certCAFilename: ""
  ## @param tls.dhParamsFilename File containing DH params (in order to support DH based ciphers)
  ##
  dhParamsFilename: ""
```

(taken from Bitnami Redis Chart values.yaml)
