### ISSUE TITLE
Nats service port name must be tcp instead of nats when deploying in a cluster with istio

### ISSUE THREAD

**Issue by marc-andre-julien-uqam** [owncloud/ocis-charts#471]
When deploying in a cluster with istio, I had to change the nats service for the installation to work.

```yaml
{{- if not .Values.messagingSystem.external.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameNats" "appNameSuffix" "") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: {{ .appName }}
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: nats # <--------------- change to tcp 
      port: 9233
      protocol: TCP
    - name: metrics-debug
      port: 9234
      protocol: TCP
{{- end }}
```
