### ISSUE TITLE
ArgoCD and autogenerated secrets

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis-charts#496]
Quick update I just defined all my secrets manually (using sealed secrets) and now I can update the helm values file without breaking anything. Let me know if this is expected/they way to do it with ArgoCD and if so will document this as well in the PR :) 

```
secretRefs:
  ldapSecretRef: "ldap-bind-secrets"
  jwtSecretRef: "jwt-secret"
  machineAuthApiKeySecretRef: "machine-auth-api-key"
  storagesystemJwtSecretRef: "storage-system-jwt-secret"
  storagesystemSecretRef: "storage-system"
  thumbnailsSecretRef: "thumbnails-transfer-secret"
  transferSecretSecretRef: "transfer-secret"
```

_Originally posted by @camrossi in https://github.com/owncloud/ocis-charts/issues/137#issuecomment-1963873548_
