### ISSUE TITLE
Default values for guest role mismatches ocis default role

### ISSUE THREAD

**Issue by blicknix** [owncloud/ocis-charts#665]
The default values for the roles mismatch the guest user role name.

```
  features:
    externalUserManagement:  
      oidc:
         mapping:
           - role_name: guest
             claim_value: ocisGuest
```

This should be user-light.
