### ISSUE TITLE
Add support for WEB_OIDC_SCOPE

### ISSUE THREAD

**Issue by d7oc** [owncloud/ocis-charts#679]
Currently the OIDC scope cannot be changed. The support should be added either by setting the environment variable `WEB_OIDC_SCOPE` or the corresponding setting see https://owncloud.dev/services/web/#example-yaml-config:

```
web:
  theme_server: https://localhost:9200
  theme_path: /themes/owncloud/theme.json
  config:
    server: https://localhost:9200
    oidc:
      metadata_url: https://localhost:9200/.well-known/openid-configuration
      authority: https://localhost:9200
      client_id: web
      response_type: code
      scope: openid profile email
      post_logout_redirect_uri: ""
```

which is missing in https://github.com/owncloud/ocis-charts/blob/main/charts/ocis/templates/web/config.yaml
