### ISSUE TITLE
Mobile + Desktop Authorization Failed, Authentik IDP

### ISSUE THREAD

**Issue by anultravioletaurora** [owncloud/ocis-charts#830]
I successfully deployed OCIS with the Helm chart, and followed [Helge Klein's blogpost](https://helgeklein.com/blog/owncloud-infinite-scale-with-openid-connect-authentication-for-home-networks/) for setting it up with my Authentik instance. 

I'm running into some intermittent issues with the iOS apps, where I run into this "Error 6" message when I try to sign in, or when I try to upload a file (after I've successfully signed in). I've been able to force quit the app and relaunch, or disconnect and reconnect within the app and that fixes it, but I'm wondering what the root cause of the issue is?

![image](https://github.com/user-attachments/assets/7941b9da-1873-4211-b7ad-9d2117d174fe)

![image](https://github.com/user-attachments/assets/27d6498d-26bd-43b4-957e-7e5be2cb59c4)

I also get this error when trying to sign in on the Linux Desktop Sync client which I'm not sure is related:
![image](https://github.com/user-attachments/assets/f795019f-415a-4f8c-be35-09670dfaf3c8)

My external user management related config is as follows:
```
      externalUserManagement:
        enabled: true
        oidc:
          accessTokenVerifyMethod: "none" # When I set this to jwt I can't login on the mobile apps at all
          skipUserInfo: "false"
          issuerURI: "https://authentik.company/application/o/owncloud/"
          webClientID: "web_provider_client_Id"
          userIDClaim: "preferred_username"
          userIDClaimAttributeMapping: "username"
          roleAssignment:
            enabled: true
            claim: groups
            mapping:
              - role_name: admin
                claim_value: "Admin"
              - role_name: user
                claim_value: "Cloud Users"
        ldap:
          writeable: false
          uri: ldap://ak-outpost-ldap.service
          certTrusted: true
          insecure: true
          bindDN: "cn=ldap_binding,ou=users,dc=ldap,dc=authentik,dc=company"
          useServerUUID: true
          user:
            schema:
              id: uid
              userName: cn
            baseDN: dc=ldap,dc=authentik,dc=company
            objectClass: user
          group:
            baseDN: ou=groups,dc=ldap,dc=authentik,dc=company
    services:
      web:
        config:
          oidc:
             tokenStorageLocal:
                enabled: false # I had tried this thinking it would fix the iOS clients but no luck
            webClientID: "web_provider_client_Id"

```
