### ISSUE TITLE
Can't provide a Client Secret to Keycloak OpenID

### ISSUE THREAD

**Issue by ivan-trinityq** [owncloud/ocis-charts#908]
*values.yaml*
```
  values:
    externalDomain: cloud.example.com
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      enabled: true
      ingressClassName: nginx
      tls:
        - secretName: cloud.example.com-tls
          hosts:
            - cloud.example.com
    features:
      externalUserManagement:
        enabled: true
        oidc:
          issuerURI: "https://sso.example.com/realms/master"
```

I didn't find in documentation, that OIDC Client should be 'web'. I found it in Logs of Keycloak

```
2025-05-08 12:56:47,210 WARN  [org.keycloak.events] (executor-thread-116) type="CODE_TO_TOKEN_ERROR", realmId="153ea60a-4892-437b-930e-ebaf52c918c4", realmName="master", clientId="web", userId="null", ipAddress="10.42.1.0", error="invalid_client_credentials", grant_type="authorization_code"
```

But how can I provide Client Secret ?

![Image](https://github.com/user-attachments/assets/be3d249c-63c9-4cff-b62b-7a0a4d6df1c5)

**Comment by wkloucek** [comment]
> I didn't find in documentation, that OIDC Client should be 'web'. 

ownCloud Web related OIDC settings can be configured here, you probably want to change `webClientID` if you want a custom OIDC client ID:

https://github.com/owncloud/ocis-charts/blob/d4ca4ea844d25f08449992f41ca8a61a1bae4d97/charts/ocis/values.yaml#L5322-L5348

ownCloud Web uses an public type OIDC client (only confidential type clients have a password)

**Comment by ivan-trinityq** [comment]
I imported realm to the Keycloak from an examlpe: https://github.com/owncloud/ocis-charts/blob/main/deployments/external-user-management/charts/keycloak/002-ocis-realm.yaml

Change a password of the user 'moss' and try to connect

it's my values.yaml:

```
  values:
    externalDomain: cloud.example.com
    features:
      externalUserManagement:
        enabled: true
        oidc:
          issuerURI: "https://sso.trinityq.de/realms/oCIS"
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      enabled: true
      ingressClassName: nginx
      tls:
        - secretName: cloud.example.com-tls
          hosts:
            - cloud.example.com
```

ownCloud uses ClientID 'web'

I see in Keycloak, that user 'moss' is connected, but get an error

![Image](https://github.com/user-attachments/assets/29d0a305-f70e-4a24-b9d1-f6e403609daa)

![Image](https://github.com/user-attachments/assets/878a3452-4bdc-4879-8daa-262d86c52f7e)
