### ISSUE TITLE
ownCloud + KeyCloak SSO + FreeIPA LDAP. Personal Spaces are not available for Admin

### ISSUE THREAD

**Issue by ivan-trinityq** [owncloud/ocis-charts#909]
We've installed:
- Helm Chart version 0.7.0 from https://github.com/owncloud/ocis-charts.git
- FreeIPA LDAP
- Keycloak (uses UsersFederation from LDAP)

**values.yaml**
```
externalDomain: cloud.example.com

features:
  externalUserManagement:
    adminUUID: owncloud-admin
    enabled: true
    ldap:
      bindDN: "uid=svc_owncloud,cn=users,cn=accounts,dc=example,dc=dom"
      group:
        baseDN: "cn=groups,cn=accounts,dc=example,dc=dom"
        schema:
          id: cn
      insecure: true
      uri: "ldap://dc01.example.com:389"
      user:
        baseDN: "cn=users,cn=accounts,dc=example,dc=dom"
        schema:
          id: uid
      writeable: false
    oidc:
      issuerURI: "https://sso.example.com/realms/ocis"
      userIDClaim: preferred_username

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  enabled: true
  ingressClassName: nginx
  tls:
    - secretName: cloud.example.com-tls
      hosts:
        - cloud.example.com

services:
  nats:
    persistence:
      accessModes:
        - ReadWriteOnce
      chownInitContainer: true
      enabled: true
  ocm:
    persistence:
      chownInitContainer: true
      accessModes:
        - ReadWriteOnce
      enabled: true
  search:
    persistence:
      accessModes:
        - ReadWriteOnce
      chownInitContainer: true
      enabled: true
  storagesystem:
    persistence:
      accessModes:
        - ReadWriteOnce
      chownInitContainer: true
      enabled: true
  storageusers:
    persistence:
      accessModes:
        - ReadWriteOnce
      chownInitContainer: true
      enabled: true
  thumbnails:
    persistence:
      accessModes:
        - ReadWriteOnce
      chownInitContainer: true
      enabled: true
  web:
    config:
      oidc:
        webClientID: owncloud-web
    persistence:
      accessModes:
        - ReadWriteOnce
      chownInitContainer: true
      enabled: true
```

After installation I cal login as user 'owncloud-admin', but we found a couple of issues:

TAB Personal is not available

![Image](https://github.com/user-attachments/assets/cb0ac26a-2b42-434e-b840-6100f7e64d02)

Also Android App can't use Personal Space , create Spaces and upload automatically Photos

![Image](https://github.com/user-attachments/assets/bb0edc71-5412-43e6-b424-d21e8814e16c)

![Image](https://github.com/user-attachments/assets/d2d2be50-6c9b-4f3a-a473-902cd9e96b89)

![Image](https://github.com/user-attachments/assets/317f4786-a15a-4622-aaa0-0a15c74ba554)

But user is the Admin:

![Image](https://github.com/user-attachments/assets/9f41e429-20bb-4b50-9177-76091eb26216)

----

Environment with `features.externalUserManagement.enabled: false`

![Image](https://github.com/user-attachments/assets/b0cb4fc1-efd9-46aa-8e02-2cd034c832fb)
